### ISSUE TITLE
installation does not work- Fatal: tailwindcss not found

### ISSUE THREAD

**Issue by Pupo1** [alonswartz/notesium#27]
I use debian 11 with npm 7.5.2 , nodejs v12.22.12 and when I try to build it from source, after the command 
`./web/app/make.sh all`

I receive the error: 
"Fatal: tailwindcss not found"

**Comment by Pupo1** [comment]
I found out that I used way too old versions of npm, nodejs, and golang.

**Comment by alonswartz** [comment]
I'm pretty certain that golang back to 1.6 (as per `go.mod`) should work. That said, I'm using:

```
go1.20.5 linux/amd64
```

As for tailwind, I'm using the [standalone-cli](https://tailwindcss.com/blog/standalone-cli) v3.1.6 (does not require node.js or npm), but here too, I'm pretty sure any later version should work.

If you come across any issues, please let me know.
