### ISSUE TITLE
WebUI - Can't clear "Note has unsaved changes" error notification

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#40]
Hey @alonswartz 

As you know I've been using the Notesium Web UI for a while now and I just hit an interesting bug.

If the "Note has unsaved changes" error notification is shown, I don't seem to be able to clear it!? I don't recall exactly what I did to get there  -perhaps trying to close an unsaved tab?

The notification doesn't seem to have a close button and I haven't found any way to get rid of it. To make it even more annoying it mostly covers the "Save" button - see screenshot below (sorry I didn't trim it). Luckily it doesn't completely cover it, but it's still annoying.

FYI I'm using Firefox on Debian Bookworm. Firefox is the latest stable installed from upstream apt repo - sorry don't have the version handy, but happy to check if it's useful.

![Screenshot 2024-05-13 at 16-17-09 Notesium Web](https://github.com/alonswartz/notesium/assets/818633/8a0eb07f-52c9-4603-b204-ec94dab26c7f)

**Comment by JedMeister** [comment]
Oops, just realised refreshing the tab fixes it. But it'd still be better if I could just close the notifcaion...

**Comment by alonswartz** [comment]
Hey @JedMeister, thanks for the report. Should be fixed in the referenced PR, will be included in the next release.
BTW - you can save a note with the `ctrl+s` keybinding ;)
