### ISSUE TITLE
webui horizontal line darker/more obvious

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#47]
As per subject: IMO the horizontal line (hr) in webui should be darker/more obvious.

Here it is in notesium:

![image](https://github.com/alonswartz/notesium/assets/818633/83b0af12-18f5-49ab-af61-501e4d2201ac)

GH light theme - IMO better contrast.

![image](https://github.com/alonswartz/notesium/assets/818633/0dec9e4c-613c-49e5-b374-99e26368a9cc)

GH dark theme - IMO even better again:

![image](https://github.com/alonswartz/notesium/assets/818633/a2d6f09d-8050-4026-a65d-1ddebdefd859)

**Comment by alonswartz** [comment]
@JedMeister I darkened the `hr` and also redid the CSS so it appears centered in the middle of the line (instead of at the top)
