### ISSUE TITLE
ability to delete note in webui

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#48]
I just accidentally created a label note that I already had - now I have the label twice which sort of sucks. So it'd nice to be able to delete a note. Preferably with a big red warning!

<s>And/or it might also be good to not be able to create a new note with the same title as one that already exists? Perhaps a new separate issue?</s>
[update] new issue opened

**Comment by JedMeister** [comment]
Also (perhaps obviously) a work around is to manually delete the duplicate note in the `~/notes` directory.

**Comment by alonswartz** [comment]
Hey @JedMeister, thanks for the feature request.

Note deletion is in progress (#53) - the backend API support should be complete along with integration tests. Next is to add support to the `web/app`. I'll keep this issue updated with progress.
