### ISSUE TITLE
Error in vim for fzf

### ISSUE THREAD

**Issue by samarulmeu** [alonswartz/notesium#5]
I tried to follow your step for integrating with vim, but I get this errors every time I try to execute a command.

    E117: Unknown function: fzf#vim#with_preview                                    
    E116: Invalid arguments for function fzf#vim#grep 

Thank you. 

L.E. : I have vim version 8.2.2434

**Comment by alonswartz** [comment]
@samarulmeu what version of fzf and fzf.vim are you using?

**Comment by alonswartz** [comment]
hmmm... it seems I'm running older versions and need to upgrade:
```
plugged/fzf.vim$ git rev-parse HEAD
7a655179a43cd431862a2bf5d297d9e55fd3f814

plugged/fzf.vim$ fzf --version
0.20.0 (30577b0)
```
I'll debug the issue once I've upgraded and push out a fix - thanks for letting me know!
In the meantime, if you'd like to try the older versions they should work...

**Comment by alonswartz** [comment]
I upgraded to the latest versions of `fzf` (binary), as well as `fzf` and `fzf.vim` vim plugins:
```$ fzf --version
0.39.0 (2023040)

plugged/fzf$ git log -1 --pretty="format:%H - %aD"
cf95e44cb4ce6f42a318abba0efa77c7311c87c9 - Wed, 26 Apr 2023 15:13:08 +0900

plugged/fzf.vim$ git log -1 --pretty="format:%H - %aD"
dc71692255b62d1f67dc55c8e51ab1aa467b1d46 - Fri, 27 Jan 2023 10:42:13 +0900
```
Everything seems to work fine, except for a minor visual tweak to hide the line number:
```diff
-  \ let spec = {'dir': $NOTESIUM_DIR, 'options': '--with-nth 2..'} |
+  \ let spec = {'dir': $NOTESIUM_DIR, 'options': '--with-nth 3..'} |
```

Are you sure you have the corresponding `fzf` vim plugin (it is required by `fzf.vim`) ?

**Comment by samarulmeu** [comment]
Sorry for the delayed answer. 1st May Holiday. 

Still the same error.

These are the versions of fzf and the corresponding plugins

    $ fzf --version                                                                                                                                                                          
    0.40.0 (fb76893)                                                                                                                                                                         
                                                                                                                                                                                             
    plugged/fzf$ git log -1 --pretty="format:%H - %aD"                                                                                                                                       
    e619b7c4f4e0da09b87a239b8f52ad909bb5f1e0 - Mon, 1 May 2023 16:18:26 +0900                                                                                                                
                                                                                                                                                                                             
    plugged/fzf.vim$ git log -1 --pretty="format:%H - %aD"                                                                                                                                   
    dc71692255b62d1f67dc55c8e51ab1aa467b1d46 - Fri, 27 Jan 2023 10:42:13 +0900

**Comment by alonswartz** [comment]
Very strange...
- Does your .vimrc include `Plug 'junegunn/fzf.vim'` ? ([similar issue](https://gist.github.com/acepukas/7600c0677d77b2aeda999fd3c3a24379?permalink_comment_id=3445362#gistcomment-3445362))
- Does `fzf` work as expected in Vim (irrelevant to notesium)? 
- If all of the above is true, could you share your .vimrc so I can try and reproduce / help debug the issue?

`Unknown function: fzf#vim#with_preview` leads me to believe the plugin isn't being loaded. The function is defined here:
```
plugged/fzf.vim$ ag 'function! fzf#vim#with_preview'
autoload/fzf/vim.vim
147:function! fzf#vim#with_preview(...)
```

**Comment by samarulmeu** [comment]
I solve the problem. In my `vimrc` I have the `fzf` and `fzf.vim` loading only when needed:

    Plug 'junegunn/fzf' , {'do': { -> fzf#install() }, 'on': ['Files', 'FZF', 'GFiles', 'History', 'Ag', 'Rg', 'Notesium*']}                                                                 
    Plug 'junegunn/fzf.vim' , {'on': ['Files', 'FZF', 'GFiles', 'History', 'Ag', 'Rg']} 

I commented the conditional part and everything works. No I should see if I have to include the Notesium commands or just remove the conditional.

Sorry for the trouble.

**Comment by alonswartz** [comment]
Glad to here it! I'll go ahead and merge https://github.com/alonswartz/notesium/pull/6 
Feel free to open another issue if you need anything.

**Comment by samarulmeu** [comment]
Maybe should you consider a vim plugin?
