### ISSUE TITLE
Allow closing tab with unsaved changes and/or closing the tab even if the original note has been deleted (from filesystem)

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#52]
I suspect this is an uncommon scenario, as I doubt others would likely follow the process I did.

Regardless, it was a PITA and interrupted my morning and I wanted to report it.

workflow that resulted in issue
--------------------------------------------

I created a new "label" note (i.e. a note with just a single word label - I often use them to "tag" notes). I saved it, but left the tab open.

I then realised my mistake when I went to add the label to an existing note.

Knowing that I couldn't delete the note (as per #48), my initial effort to resolve the issue was to delete the contents of the note.

But I got this error:
```
Error saving note
Content field is required
```
If I had my time again, at that point I would have just re-added the label (or perhaps a new one), saved and closed it. Then deleted the duplicated from the filesystem - as per my suggestion in https://github.com/alonswartz/notesium/issues/48#issuecomment-2148467070. But unfortunately I didn't do that... :sob:

Instead, I deleted the duplicate from the filesystem, with the unsaved note tab still open...

I then tried to close the open (duplicate) note tab - the one that I had jut deleted from the filesystem. I got this error:
```
Note has unsaved changes
```

So I added the original content back and tried to save. I then got this error:
```
Error saving note
Note not found
```

I then restored the file (of the duplicate labelled note). FWIW I have my notes dir as a git repo so that was easy. I tried again to save the note (with original duplicate label) but the "Note not found" error persisted!?

work around
------------------
Finally in frustration, I ensured that all my other open tabs were saved and closed the Notesium browser page.

That fixed the issue. And with the duplicate label file manually removed, everything worked as I had originally hoped (i.e. no duplicate label). FWIW I didn't need to restart the background `notesium` instance.

Unfortunately I hadn't taken note of the tabs I had open and with all the above sidetrack, I couldn't remember what I had been doing.

I was able to work around that too - at least to some extent. FWIW I ran this:
```
for file in $(ls -lt | sed -En '/Jun  5/ s|.* ([0-9a-f]*.md)|\1|p'); do head -1 $file; done
```
It wasn't perfect as I still needed to manually open the tabs using the titles, but it did the job...

**Comment by alonswartz** [comment]
@JedMeister wow, that sounds a little painful...

FWIW, note deletion support has now been added (#48 #53).

As for finding the notes modified on certain date via the CLI, this would be easier (`ctime` is also supported for created-date):
```
notesium list --sort=mtime --prefix=mtime | grep 2024-05-06
```
Alternatively, using the web interface you could use `<space> n m` (for modified) or `<space> n c` (for created). Additionally, the notes listing sidebar also supports sorting notes by `mtime`.

With regards to "saving state of open notes" so they can be restored on a page refresh, we could potentially use local or session storage, and prompt the user whether to restore/open them or not. Should be pretty simple to add, I'll have a think about that.

As for this issue **allow closing note tab with unsaved changes**, I'll take a look...
