### ISSUE TITLE
Horizontal rule not visable at all in Firefox v131.0

### ISSUE THREAD

**Issue by JedMeister** [alonswartz/notesium#71]
Since resolution of #47 it seems that the horizontal rule in no longer visible at all in Firefox (on v131.0)?! I am currently running notesium v0.5.11 and hope to update to latest soon and will update ASAP and post back to confirm that the issue is still there.

With cursor on the line with `---`:
![image](https://github.com/user-attachments/assets/8b2fc64d-0607-47de-a8e7-939fda0779a2)

With the cursor somewhere else:
![image](https://github.com/user-attachments/assets/24328bd5-757c-4f87-aedd-76788236a810)

Unfortunately I didn't note what version of Firefox I was using back when I opened the issue, nor which version of notesium I was running when I first noticed this regression. So working out when the regression occurred is a bit tricky...

Regardless, after having a bit of a poke around the notesium css, I have a resolution:

If `height: 1px;` is added in https://github.com/alonswartz/notesium/blob/905e6df2b49594255ebe9505c9b14ee7f23f0678/web/app/index.html#L47 I.e.:
```
 .cm-conceal span.cm-hr { color: transparent; background: #000000; height: 1px; display: inline-block; width: 100%; line-height: 0.05; }
```
Then it displays as expected:

![image](https://github.com/user-attachments/assets/19fdc0cf-32bd-455d-ab06-f90048da51d3)

I was inclined to open a PR, but I haven't tested any other browser than Firefox, so it probably needs some testing...

Also while I haven't test with latest (and/or master) looking at the diff of `web/app/index.html` between `v0.5.11` and `master` it looks like that specific code hasn't been touched:

```
diff --git a/web/app/index.html b/web/app/index.html
index c8999cf..e758c77 100644
--- a/web/app/index.html
+++ b/web/app/index.html
@@ -47,33 +47,6 @@
       .cm-conceal span.cm-hr { color: transparent; background: #d1d5db; display: inline-block; width: 100%; line-height: 0.05; }
       .cm-unconceal .CodeMirror-activeline span.cm-hr,
       .cm-unconceal .CodeMirror-selectedline span.cm-hr { color: #94a3b8; background: initial; display: initial; width: initial; line-height: initial;}
-
-      .CodeMirror-dialog {
-          position: absolute;
-          left: 0;
-          right: 0;
-          bottom: 0;
-          background: inherit;
-          z-index: 15;
-          overflow: hidden;
-          color: inherit;
-          padding: 8px;
-          margin-bottom: 4px;
-          border: 1px #d1d5db solid;
-          border-radius: 8px;
-          backdrop-filter: blur(8px);
-          display: flex;
-          justify-content: space-between;
-      }
-      .CodeMirror-dialog input {
-          border: none;
-          outline: 0;
-          background: 0 0;
-          width: 40em;
-          color: inherit;
-          font-family: monospace;
-          caret-color: black;
-      }
     </style>
   </head>
   <body tabindex="-1">
```

**Comment by alonswartz** [comment]
Thanks for reporting the issue @JedMeister.

It seems the issue is due to how different browsers handle very small line-height values. Firefox seems to ignore values like 0.05, while Chrome still renders them. Setting line-height to 1px appears to display correctly across both browsers.

```diff
-      .cm-conceal span.cm-hr { color: transparent; background: #d1d5db; display: inline-block; width: 100%; line-height: 0.05; }
+      .cm-conceal span.cm-hr { color: transparent; background: #d1d5db; display: inline-block; width: 100%; line-height: 1px; }
```

Could you confirm this solves the issue for you? If so, I'll include it in the next release.

**Comment by JedMeister** [comment]
Yep, that works! :grin:

**Comment by alonswartz** [comment]
This is now part of the [Notesium v0.6.1 release](https://github.com/alonswartz/notesium/releases/tag/v0.6.1). Thanks for your help and patience!
